[tools]
awscli = "latest"
bat = "latest"
buf = "latest"
claude = "latest"
difftastic = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
golangci-lint = "latest"
herdr = "latest"
hledger = "latest"
jj = "latest"
lua-language-server = "latest"
neovim = "latest"
node = "latest"
"npm:agent-browser" = "latest"
"npm:defuddle" = "latest"
"npm:oxfmt" = "latest"
"npm:oxlint" = "latest"
pi = "latest"
"npm:pnpm" = "11"
"npm:pyright" = "latest"
"npm:vercel" = "latest"
protolint = "latest"
python = "3.12"
rg = "latest"
ruff = "latest"
rust = "latest"
stylua = "latest"
tmux = "latest"
tree-sitter = "latest"
bun = "latest"
